# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('enrolment_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('assessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Assessor')),
                ('steudent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Student')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Supervisor')),
            ],
        ),
    ]
