# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 11:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thesis',
            old_name='steudent',
            new_name='student',
        ),
    ]
