# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='initials',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
