# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20170405_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='enrolment_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
