# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20170405_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='enrolment_number',
            new_name='id',
        ),
    ]
