# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_thesis_prolongation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='grade_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
