# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_thesis_grade_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='initials',
            field=models.CharField(default='NEX', max_length=10, verbose_name='Kürzel'),
            preserve_default=False,
        ),
    ]
