# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 11:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20170405_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='begin_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thesis',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2017, 4, 5, 11, 25, 28, 503171, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
