# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20170405_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessor',
            name='email',
            field=models.EmailField(max_length=80, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='assessor',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Vorname'),
        ),
        migrations.AlterField(
            model_name='assessor',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Nachname'),
        ),
    ]
