# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20170405_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Vorname'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Nachname'),
        ),
    ]
