# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20170425_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='restriction_note',
            field=models.NullBooleanField(),
        ),
    ]
