# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20170407_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='program',
            field=models.CharField(default='IB', max_length=10),
            preserve_default=False,
        ),
    ]
