# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_thesis_restriction_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='handed_in_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
