# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_thesis_handed_in_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='prolongation_reason',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='thesis',
            name='prolongation_weeks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
