# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_student_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='external',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='thesis',
            name='external_where',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='thesis',
            name='status',
            field=models.CharField(choices=[('AP', 'Angemeldet'), ('PL', 'Verlängert'), ('HI', 'Abgegeben'), ('GD', 'Benotet')], default='AP', max_length=2),
        ),
    ]
