# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20170426_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='status',
            field=models.IntegerField(choices=[(0, 'Angemeldet'), (1, 'Verlängert'), (2, 'Abgegeben'), (3, 'Benotet')], default=0),
        ),
    ]
