# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20170426_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_prof',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
