# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_user_is_prof'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_secretary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_prof',
            field=models.BooleanField(default=False),
        ),
    ]
