# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 11:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20170412_1354'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
