# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-29 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20170503_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_excom',
            field=models.BooleanField(default=False),
        ),
    ]
