# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-29 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_user_is_excom'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='excom_status',
            field=models.IntegerField(choices=[(0, 'Angemeldet'), (1, 'Genehmigt'), (2, 'Abgelehnt')], default=0),
        ),
    ]
