# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20170412_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(db_column='firstname', max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.IntegerField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(db_column='lastname', max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='program',
            field=models.CharField(db_column='program', max_length=10),
        ),
    ]
