# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-29 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_thesis_excom_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='excom_reject_reason',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
