# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20170412_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thesis',
            options={'verbose_name_plural': 'theses'},
        ),
        migrations.AddField(
            model_name='thesis',
            name='pdf_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
