# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20170418_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='student_contact',
            field=models.EmailField(default='a@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
