# Generated by Django 4.0.5 on 2022-08-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_thesis_assessor_grade_alter_assessor_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='thesis_program',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='is_head',
            field=models.BooleanField(default=False),
        ),
    ]
