# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 10:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_thesis_student_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thesis',
            old_name='pdf_key',
            new_name='surrogate_key',
        ),
    ]
