# Generated by Django 4.0.5 on 2022-10-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_thesis_thesis_program_user_is_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessor',
            name='a_title',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='akad. Grad'),
        ),
    ]
