# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 11:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_thesis_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesis',
            name='grade',
        ),
    ]
