# Generated by Django 4.0.5 on 2022-11-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_assessor_a_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessor',
            old_name='a_title',
            new_name='academic_title',
        ),
        migrations.AlterField(
            model_name='thesis',
            name='thesis_program',
            field=models.CharField(max_length=10),
        ),
    ]
