# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_thesis_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='student_contact',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
