# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_auto_20170419_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='assessor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.Assessor'),
        ),
    ]
